project_id = "tuanjmlepxdojysehytz"

[functions.register-guest]
verify_jwt = false

[functions.upload-photos]
verify_jwt = false

[functions.get-album]
verify_jwt = false

[functions.list-photos]
verify_jwt = false

[functions.list-clusters]
verify_jwt = false

[functions.cluster-photos]
verify_jwt = false

[functions.delete-photos]
verify_jwt = false

[functions.rename-cluster]
verify_jwt = false

[functions.sign-s3-upload]
verify_jwt = false

[functions.process-photos]
verify_jwt = false

