project_id = "tuanjmlepxdojysehytz"

[functions.register-guest]
verify_jwt = false

[functions.upload-photos]
verify_jwt = false

[functions.get-album]
verify_jwt = false

[functions.list-photos]
verify_jwt = false

[functions.list-clusters]
verify_jwt = false

[functions.cluster-photos]
verify_jwt = false

[functions.delete-photos]
verify_jwt = false

[functions.rename-cluster]
verify_jwt = false

[functions.sign-s3-upload]
verify_jwt = false

[functions.process-photos]
verify_jwt = false

[functions.process-photo-now]
verify_jwt = false

[functions.update-cluster]
verify_jwt = false

[functions.merge-clusters]
verify_jwt = false

[functions.list-events]
verify_jwt = false

[functions.create-event]
verify_jwt = false

[functions.update-event]
verify_jwt = false

[functions.get-public-event]
verify_jwt = false

[functions.admin-list-photos]
verify_jwt = false
